zookeeper:
    #host: 192.168.0.200
    host: 192.168.100.179
    port: 2181
    timeout:  20000
application:
    name: schedule_provider
    mongoPath:  /daq/config/mongo
    masterPath: /daq/master/um
    redisPath:  /daq/config/redis
    heartBeat:  2000
    bindAddr: 192.168.100.45
provider: 
    nodePath: /daq/provider
    port: 8888
    group:  normal
    version:  0.0.1
    timeout:  20
hive: 
    host: 192.168.0.92
    port: 10000
    dbName: public_sentiment
    driverClass: public_sentiment
    user: cloudera
    password: cloudera
hdfs: 
    nodePath: /daq/config/hdfs
spring:
      data:
          mongodb:
                host: 192.168.100.45
                port: 27017
                database: daq
      redis:
          database: 1 # database name
          host: 192.168.100.45 # server host
          password: daqsoft # server password
          port: 6379 # connection port
          pool:max-idle: 8 # pool settings :::
          pool:min-idle:  0
          pool:max-active:  8
          pool:max-wait:  -1
          #sentinel:
         #         master : # name of Redis server
         # sentinel:
          #        nodes : # comma-separated list of host:port pairs